> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [10/Dec/2018 08:58:30] "GET /detect/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/css/bootstrap-responsive.css HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/js/jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/js/eyecon-datepicker.js HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:32] "GET /static/css/eyecon-datepicker.css HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:33] "GET /static/img/glyphicons-halflings.png HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:33] "GET /static/favicon.ico HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:38] "POST /detect/1 HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
>     return func(*args, **kwargs)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 170, in detect
>     file.save(os.path.join(UPLOAD_FOLDER, filename))
> UnboundLocalError: local variable 'os' referenced before assignment
> 127.0.0.1 - - [10/Dec/2018 08:58:38] "GET /detect/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:39] "GET /detect/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:39] "GET /detect/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:39] "GET /detect/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:39] "GET /detect/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [10/Dec/2018 08:58:39] "GET /detect/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\views.py', reloading
