> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 220-276-153
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [05/Feb/2019 16:12:41] "GET / HTTP/1.1" 302 -
> 127.0.0.1 - - [05/Feb/2019 16:12:42] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [05/Feb/2019 16:12:43] "GET /static/css/bootstrap-responsive.css HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10053] An established connection was aborted by the software in your host machine
> 127.0.0.1 - - [05/Feb/2019 16:12:43] "GET /static/img/glyphicons-halflings.png HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
> 127.0.0.1 - - [05/Feb/2019 16:12:43] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
> Traceback (most recent call last):
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
> error: [Errno 10053] An established connection was aborted by the software in your host machine
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10053] An established connection was aborted by the software in your host machine
> 127.0.0.1 - - [05/Feb/2019 16:12:44] "GET /static/favicon.ico HTTP/1.1" 200 -
> Traceback (most recent call last):
> 127.0.0.1 - - [05/Feb/2019 16:12:44] "GET /static/css/eyecon-datepicker.css HTTP/1.1" 200 -
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> Traceback (most recent call last):
> error: [Errno 10053] An established connection was aborted by the software in your host machine
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\ProgramData\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10053] An established connection was aborted by the software in your host machine
> 192.168.137.240 - - [05/Feb/2019 16:13:02] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.240 - - [05/Feb/2019 16:13:02] "POST /api/db/ HTTP/1.1" 200 -
