> Initialized logger
> /home/annemirasol/remidiv2/serveus/views.py:5: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
>   from flask.ext.login import login_user, current_user, LoginManager, logout_user, login_required
> /home/annemirasol/remidiv2/serveus/forms.py:2: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
>   from flask.ext.wtf import Form
>  * Debugger is active!
>  * Debugger PIN: 322-981-763
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[32mGET /imgtest HTTP/1.1[0m" 301 -
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[1m[35mGET /imgtest/ HTTP/1.1[0m" 500 -
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/annemirasol/remidiv2/serveus/views.py", line 1512, in imgtest
>     img.create_image(img_file, 1)
>   File "/home/annemirasol/remidiv2/serveus/models.py", line 238, in create_image
>     self.case = case
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 229, in __set__
>     instance_dict(instance), value, None)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 813, in set
>     value = self.fire_replace_event(state, dict_, value, old, initiator)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 833, in fire_replace_event
>     state, value, previous, initiator or self._replace_token)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1181, in emit_backref_from_scalar_set_event
>     child_state, child_dict = instance_state(child),\
> AttributeError: 'int' object has no attribute '_sa_instance_state'
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[37mGET /imgtest/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[37mGET /imgtest/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[37mGET /imgtest/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[37mGET /imgtest/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
> 127.0.0.1 - - [12/Jun/2018 21:01:54] "[37mGET /imgtest/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
>  * Detected change in '/home/annemirasol/remidiv2/serveus/views.py', reloading
