> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [03/Feb/2019 21:38:52] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [03/Feb/2019 21:38:54] "GET /static/favicon.ico HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 21:39:10] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 21:39:10] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1165, in upload_chunk
>     z = zipfile.ZipFile(f)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\zipfile.py", line 770, in __init__
>     self._RealGetContents()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\zipfile.py", line 811, in _RealGetContents
>     raise BadZipfile, "File is not a zip file"
> BadZipfile: File is not a zip file
> 192.168.137.216 - - [03/Feb/2019 21:39:12] "POST /api/chunk/ HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\views.py', reloading
> 192.168.137.216 - - [03/Feb/2019 21:40:16] "POST /api/chunk/ HTTP/1.1" 200 -
