> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [03/Feb/2019 22:20:24] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [03/Feb/2019 22:20:29] "GET /static/favicon.ico HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:49] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:49] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:50] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:50] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:50] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:50] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:51] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:52] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:52] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:52] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:52] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:53] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:58] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:58] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:58] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:59] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:59] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:20:59] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:01] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:01] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:01] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:03] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:04] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:06] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:08] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:19] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:19] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:22] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:23] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:28] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:36] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:37] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:38] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:39] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:48] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:48] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:48] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:21:58] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:23] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:23] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\20190203_200331_dindinmt_871_32.zip.000001.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:23] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\20190203_200833_dindinmt_4274075_32.zip.000004.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\20190203_220236_dindinmt_3176764_32.zip.000097.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_202140_dindinmt_3533018_32\\20190203_202140_dindinmt_3533018_32.zip.000002.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\20190203_200331_dindinmt_871_32.zip.000001.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\20190203_200833_dindinmt_4274075_32.zip.000004.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\20190203_220236_dindinmt_3176764_32.zip.000097.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_202140_dindinmt_3533018_32\\20190203_202140_dindinmt_3533018_32.zip.000002.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:28] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:28] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\20190203_200331_dindinmt_871_32.zip.000001.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:28] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\20190203_200833_dindinmt_4274075_32.zip.000004.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:28] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\20190203_220236_dindinmt_3176764_32.zip.000097.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:28] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_202140_dindinmt_3533018_32\\20190203_202140_dindinmt_3533018_32.zip.000002.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:29] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:34] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200331_dindinmt_871_32\\20190203_200331_dindinmt_871_32.zip.000001.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:34] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_200833_dindinmt_4274075_32\\20190203_200833_dindinmt_4274075_32.zip.000004.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:34] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_220236_dindinmt_3176764_32\\20190203_220236_dindinmt_3176764_32.zip.000097.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:34] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1117, in upload_chunk
>     f.save(os.path.join(folder, filename))
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\werkzeug\datastructures.py", line 2725, in save
>     dst = open(dst, 'wb')
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_202140_dindinmt_3533018_32\\20190203_202140_dindinmt_3533018_32.zip.000002.part'
> 192.168.137.216 - - [03/Feb/2019 22:24:35] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:24:35] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:27:33] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:30:21] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:30:21] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:30:22] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:30:24] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:30:24] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:32:50] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:32:50] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:33:22] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:33:22] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:33:26] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:33:26] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:34:59] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:34:59] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:35:35] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:39:13] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:39:13] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:39:17] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:39:17] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:42:47] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:42:47] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:43:17] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:43:17] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:04] "POST /api/init/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:05] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:07] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:09] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:10] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:11] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:12] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:12] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:14] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:16] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:18] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:19] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:22] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:23] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:24] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:28] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:28] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:29] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:30] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:30] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:31] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:32] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:33] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:33] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:34] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:35] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:36] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:36] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:37] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:38] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:38] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:39] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:40] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:41] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:42] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:42] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:43] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:44] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:46] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:49] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:51] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:53] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:56] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:58] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:44:59] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:01] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:02] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:03] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:04] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:05] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:06] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:07] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:08] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:09] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:10] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:11] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:12] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:14] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:15] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:15] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:16] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:17] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:18] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:19] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:20] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:21] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:22] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:24] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:25] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:26] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:27] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:28] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:29] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:31] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:32] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:34] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:35] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:36] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:36] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:37] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:38] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:38] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:39] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:40] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:41] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:41] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:42] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:43] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:44] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:45] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:47] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:48] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:51] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:51] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:52] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:54] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:55] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:57] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:45:59] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:00] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:02] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:05] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:06] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:08] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:09] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:11] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:13] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:15] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:17] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:19] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:22] "POST /api/chunk/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:22] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_224355_dindinmt_3972961_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:46:22] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:46:22] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:47:24] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.216 - - [03/Feb/2019 22:47:24] "POST /api/chunk/ HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py", line 1183, in upload_chunk
>     with open(os.path.join(folder, 'cipherZipFile.zip'), 'rb') as f:
> IOError: [Errno 2] No such file or directory: 'C:/Users/gherz-PC/Desktop/remidiv2\\upload/20190203_224355_dindinmt_3972961_32\\cipherZipFile.zip'
> 192.168.137.216 - - [03/Feb/2019 22:47:24] "POST /api/db/ HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\views.py', reloading
